"""initial complete schema

Revision ID: 784a42a09e36
Revises:
Create Date: 2026-08-12 10:58:11.419813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784a42a09e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_deleted_at'), 'admin_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('bidders',
    sa.Column('display_alias', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_carts_expires_at'), 'carts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_carts_status'), 'carts', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_collections_status'), 'collections', ['status'], unique=False)
    op.create_table('contact_messages',
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=140), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_version', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol')
    )
    op.create_index('ix_contact_status_created', 'contact_messages', ['status', 'created_at'], unique=False)
    op.create_table('content_entries',
    sa.Column('key', sa.String(length=140), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('event_editions',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_event_editions_starts_at'), 'event_editions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_event_editions_status'), 'event_editions', ['status'], unique=False)
    op.create_table('gallery_tags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key_hash', name='uq_idempotency_scope_key')
    )
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=30), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('login_attempts',
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_subject_created', 'login_attempts', ['subject_hash', 'created_at'], unique=False)
    op.create_table('media_reconciliation_tasks',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_reconciliation_tasks_resource_id'), 'media_reconciliation_tasks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_media_reconciliation_tasks_status'), 'media_reconciliation_tasks', ['status'], unique=False)
    op.create_table('participation_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('extra_fields_json', sa.Text(), nullable=False),
    sa.Column('accepts_file', sa.Boolean(), nullable=False),
    sa.Column('accepts_link', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_participation_categories_active'), 'participation_categories', ['active'], unique=False)
    op.create_table('partners',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=False),
    sa.Column('logo_alt', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_partners_active'), 'partners', ['active'], unique=False)
    op.create_table('permissions',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rate_limit_events',
    sa.Column('bucket_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_bucket_created', 'rate_limit_events', ['bucket_hash', 'created_at'], unique=False)
    op.create_table('roles',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('social_links',
    sa.Column('network', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sa.String(length=140), nullable=False),
    sa.Column('postal_code', sa.String(length=12), nullable=False),
    sa.Column('street', sa.String(length=180), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('complement', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=True),
    sa.Column('user_session_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_sessions_revoked_at'), 'admin_sessions', ['revoked_at'], unique=False)
    op.create_index('ix_admin_sessions_user_expires', 'admin_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_resource_created', 'audit_logs', ['resource_type', 'created_at'], unique=False)
    op.create_table('backup_records',
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('location_label', sa.String(length=180), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'version', name='uq_content_entry_version')
    )
    op.create_index(op.f('ix_content_versions_entry_id'), 'content_versions', ['entry_id'], unique=False)
    op.create_index(op.f('ix_content_versions_status'), 'content_versions', ['status'], unique=False)
    op.create_table('data_exports',
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('export_type', sa.String(length=40), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_albums',
    sa.Column('edition_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['event_editions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_gallery_albums_edition_id'), 'gallery_albums', ['edition_id'], unique=False)
    op.create_index(op.f('ix_gallery_albums_status'), 'gallery_albums', ['status'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_verifier', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_table('partner_editions',
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['event_editions.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('partner_id', 'edition_id')
    )
    op.create_table('privacy_requests',
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('subject_reference_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol')
    )
    op.create_index(op.f('ix_privacy_requests_subject_reference_hash'), 'privacy_requests', ['subject_reference_hash'], unique=False)
    op.create_table('products',
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('composition', sa.String(length=500), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name='ck_products_price_nonnegative'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_products_collection_id'), 'products', ['collection_id'], unique=False)
    op.create_index(op.f('ix_products_featured'), 'products', ['featured'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('ix_products_status_order', 'products', ['status', 'display_order'], unique=False)
    op.create_table('registrations',
    sa.Column('protocol', sa.String(length=24), nullable=False),
    sa.Column('upload_token_hash', sa.String(length=64), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=False),
    sa.Column('professional_name', sa.String(length=140), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('presentation', sa.Text(), nullable=False),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_version', sa.String(length=30), nullable=False),
    sa.Column('consent_purpose', sa.String(length=160), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['participation_categories.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['event_editions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol')
    )
    op.create_index(op.f('ix_registrations_anonymized_at'), 'registrations', ['anonymized_at'], unique=False)
    op.create_index(op.f('ix_registrations_assigned_to_id'), 'registrations', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_registrations_deleted_at'), 'registrations', ['deleted_at'], unique=False)
    op.create_index('ix_registrations_edition_category', 'registrations', ['edition_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_registrations_edition_id'), 'registrations', ['edition_id'], unique=False)
    op.create_index(op.f('ix_registrations_phone_e164'), 'registrations', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_registrations_priority'), 'registrations', ['priority'], unique=False)
    op.create_index(op.f('ix_registrations_status'), 'registrations', ['status'], unique=False)
    op.create_index('ix_registrations_status_created', 'registrations', ['status', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=140), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('communication_logs',
    sa.Column('registration_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient_hash', sa.String(length=64), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_communication_idempotency')
    )
    op.create_index(op.f('ix_communication_logs_registration_id'), 'communication_logs', ['registration_id'], unique=False)
    op.create_table('gallery_media',
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('caption', sa.String(length=600), nullable=True),
    sa.Column('alt_text', sa.String(length=180), nullable=False),
    sa.Column('credit', sa.String(length=180), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_gallery_media_category'), 'gallery_media', ['category'], unique=False)
    op.create_index('ix_gallery_status_order', 'gallery_media', ['status', 'display_order'], unique=False)
    op.create_table('orders',
    sa.Column('public_code', sa.String(length=24), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('fulfillment_method', sa.String(length=30), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('shipping_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('terms_version', sa.String(length=30), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('shipping_cents >= 0', name='ck_orders_shipping_nonnegative'),
    sa.CheckConstraint('subtotal_cents >= 0', name='ck_orders_subtotal_nonnegative'),
    sa.CheckConstraint('total_cents >= 0', name='ck_orders_total_nonnegative'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('product_media',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=180), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_media_product_id'), 'product_media', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('price_override_cents', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reserved_quantity <= stock_quantity', name='ck_variants_reserved_within_stock'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_variants_reserved_nonnegative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_variants_stock_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('profiles',
    sa.Column('registration_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('display_name', sa.String(length=140), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_profiles_featured'), 'profiles', ['featured'], unique=False)
    op.create_index(op.f('ix_profiles_status'), 'profiles', ['status'], unique=False)
    op.create_table('registration_files',
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('safe_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('reconciliation_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_registration_files_registration_id'), 'registration_files', ['registration_id'], unique=False)
    op.create_index(op.f('ix_registration_files_sha256'), 'registration_files', ['sha256'], unique=False)
    op.create_table('registration_notes',
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_notes_registration_id'), 'registration_notes', ['registration_id'], unique=False)
    op.create_table('registration_status_history',
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_status_history_registration_id'), 'registration_status_history', ['registration_id'], unique=False)
    op.create_table('artworks',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('artist_name', sa.String(length=140), nullable=False),
    sa.Column('artist_profile_id', sa.Uuid(), nullable=True),
    sa.Column('technique', sa.String(length=140), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_artworks_artist_profile_id'), 'artworks', ['artist_profile_id'], unique=False)
    op.create_index(op.f('ix_artworks_status'), 'artworks', ['status'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_items_quantity_positive'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_item_unique_active', 'cart_items', ['cart_id', 'variant_id'], unique=False)
    op.create_table('fulfillments',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillments_order_id'), 'fulfillments', ['order_id'], unique=False)
    op.create_table('gallery_media_tags',
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['gallery_media.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['gallery_tags.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'tag_id')
    )
    op.create_table('inventory_movements',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_order_id'), 'inventory_movements', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_variant_id'), 'inventory_movements', ['variant_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_reservation_expiry', 'inventory_reservations', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_order_id'), 'inventory_reservations', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('product_name_snapshot', sa.String(length=180), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=80), nullable=False),
    sa.Column('variant_snapshot', sa.String(length=120), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.CheckConstraint('unit_price_cents >= 0', name='ck_order_items_price_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_provider_reference', 'payments', ['provider', 'provider_reference'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('alt_text', sa.String(length=180), nullable=False),
    sa.Column('credit', sa.String(length=180), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_assets_profile_id'), 'portfolio_assets', ['profile_id'], unique=False)
    op.create_table('profile_categories',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['participation_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'category_id')
    )
    op.create_table('artwork_media',
    sa.Column('artwork_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=180), nullable=False),
    sa.Column('credit', sa.String(length=180), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artwork_media_artwork_id'), 'artwork_media', ['artwork_id'], unique=False)
    op.create_table('auction_lots',
    sa.Column('artwork_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('starting_bid_cents', sa.Integer(), nullable=False),
    sa.Column('minimum_increment_cents', sa.Integer(), nullable=False),
    sa.Column('current_bid_cents', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('winner_bid_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('minimum_increment_cents > 0', name='ck_lots_increment_positive'),
    sa.CheckConstraint('starting_bid_cents >= 0', name='ck_lots_start_nonnegative'),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artwork_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_auction_lots_status'), 'auction_lots', ['status'], unique=False)
    op.create_index('ix_lots_status_closes', 'auction_lots', ['status', 'closes_at'], unique=False)
    op.create_table('auction_lot_status_history',
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_lot_status_history_lot_id'), 'auction_lot_status_history', ['lot_id'], unique=False)
    op.create_table('bids',
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('terms_version', sa.String(length=30), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_bids_amount_positive'),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['auction_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_bids_lot_amount_created', 'bids', ['lot_id', 'amount_cents', 'created_at'], unique=False)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_foreign_key(
        'fk_content_entries_current_version_id',
        'content_entries', 'content_versions', ['current_version_id'], ['id']
    )
    op.create_foreign_key(
        'fk_auction_lots_winner_bid_id',
        'auction_lots', 'bids', ['winner_bid_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_auction_lots_winner_bid_id', 'auction_lots', type_='foreignkey')
    op.drop_constraint(
        'fk_content_entries_current_version_id', 'content_entries', type_='foreignkey'
    )
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index('ix_bids_lot_amount_created', table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_auction_lot_status_history_lot_id'), table_name='auction_lot_status_history')
    op.drop_table('auction_lot_status_history')
    op.drop_index('ix_lots_status_closes', table_name='auction_lots')
    op.drop_index(op.f('ix_auction_lots_status'), table_name='auction_lots')
    op.drop_table('auction_lots')
    op.drop_index(op.f('ix_artwork_media_artwork_id'), table_name='artwork_media')
    op.drop_table('artwork_media')
    op.drop_table('profile_categories')
    op.drop_index(op.f('ix_portfolio_assets_profile_id'), table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index('ix_payments_provider_reference', table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_inventory_reservations_order_id'), table_name='inventory_reservations')
    op.drop_index('ix_inventory_reservation_expiry', table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index(op.f('ix_inventory_movements_variant_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_order_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_table('gallery_media_tags')
    op.drop_index(op.f('ix_fulfillments_order_id'), table_name='fulfillments')
    op.drop_table('fulfillments')
    op.drop_index('ix_cart_item_unique_active', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_artworks_status'), table_name='artworks')
    op.drop_index(op.f('ix_artworks_artist_profile_id'), table_name='artworks')
    op.drop_table('artworks')
    op.drop_index(op.f('ix_registration_status_history_registration_id'), table_name='registration_status_history')
    op.drop_table('registration_status_history')
    op.drop_index(op.f('ix_registration_notes_registration_id'), table_name='registration_notes')
    op.drop_table('registration_notes')
    op.drop_index(op.f('ix_registration_files_sha256'), table_name='registration_files')
    op.drop_index(op.f('ix_registration_files_registration_id'), table_name='registration_files')
    op.drop_table('registration_files')
    op.drop_index(op.f('ix_profiles_status'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_featured'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_media_product_id'), table_name='product_media')
    op.drop_table('product_media')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_gallery_status_order', table_name='gallery_media')
    op.drop_index(op.f('ix_gallery_media_category'), table_name='gallery_media')
    op.drop_table('gallery_media')
    op.drop_index(op.f('ix_communication_logs_registration_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_table('user_roles')
    op.drop_table('site_settings')
    op.drop_table('role_permissions')
    op.drop_index('ix_registrations_status_created', table_name='registrations')
    op.drop_index(op.f('ix_registrations_status'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_priority'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_phone_e164'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_edition_id'), table_name='registrations')
    op.drop_index('ix_registrations_edition_category', table_name='registrations')
    op.drop_index(op.f('ix_registrations_deleted_at'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_assigned_to_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_anonymized_at'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index('ix_products_status_order', table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_featured'), table_name='products')
    op.drop_index(op.f('ix_products_collection_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_privacy_requests_subject_reference_hash'), table_name='privacy_requests')
    op.drop_table('privacy_requests')
    op.drop_table('partner_editions')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_gallery_albums_status'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_edition_id'), table_name='gallery_albums')
    op.drop_table('gallery_albums')
    op.drop_table('data_exports')
    op.drop_index(op.f('ix_content_versions_status'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_entry_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_table('backup_records')
    op.drop_index('ix_audit_resource_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_admin_sessions_user_expires', table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_revoked_at'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('social_links')
    op.drop_table('roles')
    op.drop_index('ix_rate_limit_bucket_created', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_partners_active'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_participation_categories_active'), table_name='participation_categories')
    op.drop_table('participation_categories')
    op.drop_index(op.f('ix_media_reconciliation_tasks_status'), table_name='media_reconciliation_tasks')
    op.drop_index(op.f('ix_media_reconciliation_tasks_resource_id'), table_name='media_reconciliation_tasks')
    op.drop_table('media_reconciliation_tasks')
    op.drop_index('ix_login_attempts_subject_created', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('gallery_tags')
    op.drop_index(op.f('ix_event_editions_status'), table_name='event_editions')
    op.drop_index(op.f('ix_event_editions_starts_at'), table_name='event_editions')
    op.drop_table('event_editions')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('content_entries')
    op.drop_index('ix_contact_status_created', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_collections_status'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_carts_status'), table_name='carts')
    op.drop_index(op.f('ix_carts_expires_at'), table_name='carts')
    op.drop_table('carts')
    op.drop_table('bidders')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_deleted_at'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
