import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { AddToCart } from "@/components/add-to-cart";
import { brl,type Envelope } from "@/lib/api";
export const dynamic="force-dynamic";
type Product={slug:string;name:string;description:string;composition?:string;price_cents:number;available:boolean;media:{url:string;alt:string;width?:number;height?:number}[];variants:{id:string;name:string;size?:string;color?:string;price_cents:number;available_quantity:number}[]};
async function getProduct(slug:string){try{const response=await fetch(`${process.env.INTERNAL_API_URL??"http://127.0.0.1:5000"}/api/v1/products/${encodeURIComponent(slug)}`,{next:{revalidate:60}});if(response.status===404)return null;return (await response.json() as Envelope<Product>).data;}catch{return null}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const product=await getProduct(slug);return {title:product?.name??"Produto",description:product?.description,alternates:{canonical:`/loja/${slug}`}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=await getProduct(slug);if(!product)notFound();const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.name,description:product.description,offers:{"@type":"Offer",priceCurrency:"BRL",price:(product.price_cents/100).toFixed(2),availability:product.available?"https://schema.org/InStock":"https://schema.org/OutOfStock"}};return <section className="section"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="container grid cards"><div>{product.media.length?product.media.map(item=><Image key={item.url} src={item.url} alt={item.alt} width={item.width??900} height={item.height??900}/>):<div className="empty">As fotos reais deste produto ainda não foram publicadas.</div>}</div><div><p className="eyebrow">Coleção Movimento 7</p><h1>{product.name}</h1><p className="lead">{product.description}</p>{product.composition&&<p>Composição: {product.composition}</p>}<p><strong>{brl(product.price_cents)}</strong></p><AddToCart variants={product.variants}/></div></div></section>}
